on: [push]
# on: 
#   schedule: 
#   # 00:01 
#   # UTC时间 中国时间 -8
#   - cron: '1 16 * * *'
# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
# │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
# │ │ │ │ │
# │ │ │ │ │
# │ │ │ │ │
# * * * * *



jobs:
  create_issues:
    runs-on: ubuntu-latest
    name: create issues
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: create issues
        uses: ./ # Uses an action in the root directory
        
        # 传参用
        with:
          token: ${{secrets.TOKEN}}
    